/**
 * Prebuild Script — Runs during Vercel build BEFORE vite build
 * 
 * Flow:
 *   1. Connects to MongoDB
 *   2. Fetches all published pages
 *   3. Writes each page as individual JSON: frontend/src/data/pages/{slug}.json
 *   4. Updates the index file: frontend/src/data/staticContent.js
 * 
 * If MongoDB is unavailable, existing JSON files are used as fallback.
 */
const mongoose = require('mongoose');
const fs = require('fs');
const path = require('path');

const sectionSchema = new mongoose.Schema({
  sectionId: String, order: Number, heading: String, subheading: String,
  text: String, image: String, bgColor: String,
  items: [{ title: String, description: String, icon: String, image: String, link: String }]
}, { _id: false });

const pageContentSchema = new mongoose.Schema({
  pageSlug: { type: String, required: true, unique: true },
  title: String, metaDescription: String,
  sections: [sectionSchema],
  isPublished: { type: Boolean, default: true }
}, { timestamps: true });

const PageContent = mongoose.model('PageContent', pageContentSchema);

const PAGES_DIR = path.join(__dirname, '..', 'frontend', 'src', 'data', 'pages');
const INDEX_PATH = path.join(__dirname, '..', 'frontend', 'src', 'data', 'staticContent.js');

function cleanPage(page) {
  return {
    pageSlug: page.pageSlug,
    title: page.title,
    isPublished: page.isPublished,
    metaDescription: page.metaDescription,
    sections: (page.sections || []).map(s => {
      const clean = { sectionId: s.sectionId, order: s.order };
      if (s.heading) clean.heading = s.heading;
      if (s.subheading) clean.subheading = s.subheading;
      if (s.text) clean.text = s.text;
      if (s.image) clean.image = s.image;
      if (s.bgColor) clean.bgColor = s.bgColor;
      if (s.items && s.items.length > 0) {
        clean.items = s.items.map(item => {
          const ci = {};
          if (item.title) ci.title = item.title;
          if (item.description) ci.description = item.description;
          if (item.icon) ci.icon = item.icon;
          if (item.image) ci.image = item.image;
          if (item.link) ci.link = item.link;
          return ci;
        });
      }
      return clean;
    })
  };
}

function generateIndex(slugs) {
  const imports = slugs.map(slug => {
    const varName = slug.replace(/-/g, '_');
    return `import ${varName} from './pages/${slug}.json';`;
  });

  const entries = slugs.map(slug => {
    const varName = slug.replace(/-/g, '_');
    return `  '${slug}': ${varName}`;
  });

  return `// Auto-generated by prebuild script — DO NOT EDIT MANUALLY
// Last updated: ${new Date().toISOString()}
${imports.join('\n')}

const staticContent = {
${entries.join(',\n')}
};

export default staticContent;
`;
}

async function prebuild() {
  const MONGO_URI = process.env.MONGO_URI;

  if (!MONGO_URI) {
    console.log('⚠️  No MONGO_URI — using existing JSON files');
    return;
  }

  try {
    console.log('🔄 Connecting to MongoDB...');
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected!');

    const pages = await PageContent.find({ isPublished: true }).lean();

    if (!pages || pages.length === 0) {
      console.log('⚠️  No pages in DB — using existing JSON files');
      await mongoose.disconnect();
      return;
    }

    // Ensure pages directory exists
    if (!fs.existsSync(PAGES_DIR)) {
      fs.mkdirSync(PAGES_DIR, { recursive: true });
    }

    const slugs = [];

    for (const page of pages) {
      const cleaned = cleanPage(page);
      const filePath = path.join(PAGES_DIR, `${page.pageSlug}.json`);
      fs.writeFileSync(filePath, JSON.stringify(cleaned, null, 2), 'utf8');
      slugs.push(page.pageSlug);
      console.log(`  📄 ${page.pageSlug}.json`);
    }

    // Write the index file
    fs.writeFileSync(INDEX_PATH, generateIndex(slugs), 'utf8');

    console.log(`✅ Updated ${pages.length} page JSONs + index`);
    await mongoose.disconnect();
  } catch (err) {
    console.error('❌ Prebuild failed:', err.message);
    console.log('⚠️  Using existing JSON files as fallback');
    try { await mongoose.disconnect(); } catch(e) {}
  }
}

prebuild();
